Add include directory
Currently, on our Linux installation, with FFTW available, we get

```
$ make
g++ -c -O3 main.cpp mcmc.cpp cholesky.cpp randgen.cpp mybspline.cpp hrf.cpp kernel_reg.cpp knots.cpp statistics.cpp config_info.cpp dlm.cpp
hrf.cpp:13:10: fatal error: fftw3.h: No such file or directory
 #include <fftw3.h>
          ^~~~~~~~~
compilation terminated.
make: *** [hrf.o] Error 1
```

This is because there isn't a `-I$FFTW_HOME` option on the compilation line.  Adding `$(INC)` fixes this issue.